# Feature Engineering

In [1]:
import pandas as pd

In [49]:
df = pd.read_csv("../data/processed/clean_tracks.csv")

### New feature : mode_score

In [51]:
df["mood_score"] = (df["valence"] + df["energy"] )/2
df[["mood_score"]]

        mood_score
0          0.58800
1          0.21650
2          0.23950
3          0.10130
4          0.30500
...            ...
113544     0.13445
113545     0.07600
113546     0.53600
113547     0.45950
113548     0.59750

[113549 rows x 1 columns]

### New feature : party_score

In [58]:
df["party_score"] = (df["danceability"] + df["energy"]) /2
df[["party_score"]]

        party_score
0            0.5685
1            0.2930
2            0.3985
3            0.1628
4            0.5305
...             ...
113544       0.2035
113545       0.1455
113546       0.4790
113547       0.5465
113548       0.5065

[113549 rows x 1 columns]

### New feature: popularity_tier

In [61]:
df["popularity_tier"] =  pd.cut(    
    df["popularity"],
    bins= [0, 30 , 60 ,100], 
    labels= ["Low", "Medium", "High"],
    include_lowest= True  )

df[["popularity","popularity_tier"]].sample(10)

        popularity popularity_tier
18912            2             Low
102475          31          Medium
38655           38          Medium
54856           64            High
97996           25             Low
95106           29             Low
77021           46          Medium
33882           54          Medium
103252           0             Low
23536           50          Medium

### New feature : tempo_levels

In [60]:
df["tempo_level"] = pd.cut(
    df["tempo"],
    bins= [0, 90, 130 , 250 ] ,
    labels= ["Slow", "Medium", "Fast"],
    include_lowest = True
)

df[["tempo", "tempo_level"]].sample(10)

         tempo tempo_level
50633  159.953        Fast
99341  150.566        Fast
5026   119.957      Medium
95169  106.052      Medium
38269   71.792        Slow
39247  119.968      Medium
19129  134.944        Fast
66746  175.998        Fast
69307  145.044        Fast
51557   87.015        Slow

In [62]:
df.to_csv('../data/processed/featured_tracks.csv', index=False)

## SUMMARY >
- Created mood_score by combining features related to a song's emotional characteristics
- Created party_score byp combining [danceability and energy] to represent how suitable a song is for dancing or parties
- Created popularity_tier by categorizing the continuous popularity score into [Low, Medium, and High] groups. This can be useful for  classification tasks
- Created tempo_level by grouping the song's tempo (measured in beats per minute, BPM) into categories such as [Slow, Medium, and Fast]